// Generated by https://quicktype.io

export interface LocalUser {
    _id:       string;
    email:     string;
    createdAt: string;
    updatedAt: string;
    __v:       number;
    token:     Token;
}

export interface Token {
    accessToken: string;
}
